[#fix]
= Fix Virtual Machine snapshot restore buttons are grayed out

== Scenario

In this scenario, a Virtual Machine named `exercise7` is currently in the `Running` state and has an existing snapshot that the user wants to restore. However, the user has noticed that the buttons to restore the snapshot are grayed out, making it impossible to proceed with the restoration.

Your task is to investigate the steps taken by the user to restore the snapshot and resolve the issue.

The steps to fix exercise7 are:

== Console
----
1. Login to Openshift console using the assigned user account
2. Go to virtualization - virtual machine - select project for the assigned user account - look for VM status

#TODO

----

== Command Line (CLI)

1. Login to Openshift server API using the assigned user account with `oc` command if not logged in.

[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

[start=2]
2. Go to the assigned namespace-{user}

[source,sh,role=execute,subs="attributes"]
----
oc project namespace-{user}
----

[start=3]
3. Stop the virtual machine `exercise7`

[source,sh,role=execute,subs="attributes"]
----
virtctl stop exercise7
----

[source]
----
VM exercise7 was scheduled to stop
----

[start=4]
4. Restore the virtual machine snapshot. In the {user} home directory there's `exercise7-restoresnapshot.yaml` file. Check it.

[source,sh,role=execute,subs="attributes"]
----
cat /home/{user}/exercise7-restoresnapshot.yaml
----

[start=5]
5. Apply it 

[source,sh,role=execute,subs="attributes"]
----
oc apply -f /home/{user}/exercise7-restoresnapshot.yaml
----

[source]
----
virtualmachinerestore.snapshot.kubevirt.io/restore-exercise7-snapshot created
----

[start=6]
6. Check that VirtualMachineRestore has been created

[source,sh,role=execute,subs="attributes"]
----
oc get VirtualMachineRestore restore-exercise7-snapshot -n namespace-{user}
----

[source]
----
NAME                         TARGETKIND       TARGETNAME   COMPLETE   RESTORETIME   ERROR
restore-exercise7-snapshot   VirtualMachine   exercise7    true       38s
----

