[#fix]
= Fix Application is not being accessed externally

== Scenario

The application is running on a virtual machine `exercise3` and is intended to be accessible externally through https://exercise3-namespace-{user}.apps.cluster-{guid}.dynamic.redhatworkshops.io, but it’s currently facing connectivity issues.

The primary goal in this scenario is to investigate the cause of the issue by examining the OpenShift network components involved in accessing the application within the OpenShift cluster.

Your task is to identify the root cause and resolve the issue.

The steps to fix exercise3 are:

== Console
----
1. Login to Openshift console using the assigned user account
2. Go to virtualization - virtual machine - select project for the assigned user account - look for VM status
3. Go to Networking - look for the name exercise3 and location - click the location (https route)
4. In the new browser tab - check the error status (The application is currently not serving requests at this endpoint. It may not have been started or is still starting.)
5. Go to Network - Services - Check exercise3 services - Look for target port (80) and IP
6. Go to Workloads - Pod - Select curlimage pod - Terminal
7. Try to do curl from the pod to service IP and port (80)
8. The service should be accessible with message: Hello from exercise3, you are doing a great job!
9. Go to Network - Routes - Check exercise3 routes - Look for target port (8080)
10. Edit route for exercise3 in yaml and update the target port into 80 - Save
11. Access the route URL and application should be accessible
----

== Command line (CLI)
- Login to Openshift server API using the assigned user account with `oc` command

[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

- Go to assigned namespace-{user}

[source,sh,role=execute,subs="attributes"]
----
oc project namespace-{user}
----

- Check the service details of exercise3 and get details for IP and Port (80)

[source,sh,role=execute,subs="attributes"]
----
oc describe svc exercise3
----

- Go to the curlimage pod

[source,sh,role=execute,subs="attributes"]
----
oc rsh pod curlimage
----

- Curl the IP and port from service in the curlimage pod

[source,sh,role=execute,subs="attributes"]
----
curl on svc
----

The curl should be working 

====
Hello from exercise3, you are doing a great job!
====

- Check the route target port - Wrong target port (8080)

[source,sh,role=execute,subs="attributes"]
----
oc describe route exercise3
----

- Edit the route exercise3 and change target port to 80)

[source,sh,role=execute,subs="attributes"]
----
oc edit route exercise3
----

- Test the application

The application is available on https://exercise3-namespace-{user}.apps.cluster-{guid}.dynamic.redhatworkshops.io