[#fix]
= Additional disk unaccessible in Virtual Machine

== Scenario

The user is reporting that the additional disk in the `exercise5` virtual machine does not show up in the lists when running the `fdisk` or `lsblk` command. The user would like to create a disk named `exercise5-vol-data1` and mount it to the virtual machine named `exercise5`

NOTE: Your task is to troubleshoot and resolve the issue so that the `exercise5-vol-data1` disk is showing when the user runs the `lsblk` or `fdisk` command.

NOTE: Virtual machine credentials - lab-user/redhat1

The steps to fix exercise5 are:

=== Console
----
1. Login to Openshift console using the assigned user account
2. Go to Virtualization - VirtualMachines - select project for the assigned user account - look for VM exercise5 status (Running)
3. From the VM menu connect to console of exercise5 and login with lab-user credential
4. From the RHEL 9 run command fdsisk -l or lbslk. The assigned additional disk not exist.
5. From the Openshift Menu - Storage - PersistentVolumeClaims (PVC) - Check the additional disk PVC (exercise5-vol-data1) status is Pending - Not bound
6. Go to Virtualization - VirtualMachines - VirtualMachine details - Click Configuration - Select Storage - Look for additional disk (exercise5-vol-data1)
7. From the additional disk (exercise5-vol-data1) - Select the source - Look in the yaml - Search for storageClassName (pending status from the disk should be ocs-external-storagecluster-cephfs)
8. Back to VirtualMachine details - Click Configuration - Select Storage - Detach exercise5-vol-data1 disk from the three dots menu
9 Recreate exercise5-vol-data1 disk by clicking Add disk - Put the name exercise5-vol-data1 - Make sure the StorageClass is ocs-external-storagecluster-ceph-rbd and let default for other value - Save
10. From the Openshift Menu - Storage - PersistentVolumeClaims (PVC) - Check the additional disk PVC (exercise5-vol-data1) status is Bound
11. From the VM menu connect to console of exercise5 and login with lab-user credential.
12. From the RHEL 9 run command fdsisk -l or lbslk. The assigned additional 30GiB disk should be there now and readu to format and mount as filesystem by the user.
----

=== Command line (CLI)

1. Login to Openshift server API using the assigned user account with `oc` command if not logged in.

.OpenShift login command
[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

[start=2]
2. Go to the assigned namespace-{user}

[source,sh,role=execute,subs="attributes"]
----
oc project namespace-{user}
----

[start=3]
3. List the virtual machines


[source,sh,role=execute,subs="attributes"]
----
oc get virtualmachine
----

[start=4]
5. Check the additional data disk `exercise5-vol-data1` Datavolume is empty

[source,sh,role=execute,subs="attributes"]
----
oc get datavolume
----

[start=5]
4. Check the additional data disk `exercise5-vol-data1` does not have no `PersistentVolumeClaims` associated

[source,sh,role=execute,subs="attributes"]
----
oc get pvc
----

[start=6]
6. Check the configuration of `exercise5-vol-data1` Datavolume and verify that 
there is a misconfigured defaultStorageClass 

[source,sh,role=execute,subs="attributes"]
----
oc get datavolume exercise5-vol-data1 -n namespace-{user} -o yaml
----

[start=7]
7. Delete the the datavolume exercise5-vol-data1

[source,sh,role=execute,subs="attributes"]
----
oc delete datavolume exercise5-vol-data1
----

[start=8]
8. Create again the DataVolume by using the `storageClassName` of `ocs-storagecluster-ceph-rbd` with the name `exercise5-vol-data1` and using 30GiB size.

[source,sh,role=execute]
----
oc create -f - <<EOF
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: exercise5-vol-data1
spec:
  preallocation: false
  source:
    blank: {}
  storage:
    resources:
      requests:
        storage: 30Gi
    storageClassName: ocs-storagecluster-ceph-rbd
EOF
----

[start=9]
9. Check the status of exercise5-vol-data1 and wait for the additional disk to be provisioned

[source,sh,role=execute,subs="attributes"]
----
watch oc get pvc
----

[start=10]
10. Go to virtual machine console of exercise5 and login using lab-user credential

[source,sh,role=execute,subs="attributes"]
----
virtctl console exercise5
----

[start=11]
11. Check the disk availability using `lsblk` or `fdisk -l` command. The new additional disk from `exercise5-vol-data1` should be there and ready to be format and mount by the user.

=== What you learned

In this exercise, you learned that disks are not presented to virtual machines until Persistent Volume Claims (PVCs) are created. 
To change the `defaultStorageClass` of a data volume in OpenShift Virtualization, you need to delete the existing data volume and create a new one with the desired storage class.