[#scenario]
= Virtual Machine with performance degraded

== Scenario

In this scenario, a Virtual Machine named `exercise4` is currently `Running`. The development team has reported a performance issue with an application hosted inside this VM.

Your task is to investigate the problem, starting with an analysis of the VM's resource usage, including CPU, memory, disk I/O and so on. 
Adjusting Virtual Machine compute resources is allowed in this lab; however, `no reboot` is mandatory.

NOTE: The goal is to identify any bottlenecks or misconfigurations and implement optimizations to enhance the application's efficiency within the virtualized infrastructure.

== Executing the lab script

In this exercise setup, you first need to access the bastion trough `{bastion_public_hostname}` to gain entry into the lab environment. From the terminal, access the bastion node using SSH if you are not connected yet.

[source,sh,role=execute,subs="attributes"]
----
ssh {user}@{bastion_public_hostname} -p {bastion_ssh_port}
----

Once connected to the bastion host run the command to break the lab.

[source,sh,role=execute,subs="attributes"]
----
lab break exercise4
----