[#scenario]
= Virtual Machine with performance degraded

== Scenario

In this scenario, a Virtual Machine named `exercise4` is currently Running. The development team has reported a performance issue with an application hosted inside this VM.

Your task is to investigate the problem, starting with analyzing the VM’s resource usage, including CPU, memory, disk I/O, etc. Adjusting Virtual Machine compute resources is allowed in this lab; however, `no reboot` is mandatory.

NOTE: The goal is to identify bottlenecks or misconfigurations and implement optimizations to enhance the application's efficiency within the virtualized infrastructure.

== Executing the lab script

In this exercise setup, ensure you are logged in to the bastion and OCP cluster as {user}

[source,sh,role=execute,subs="attributes"]
----
ifeval::["{cloud_provider}" == "gcp"]
ssh {user}@{bastion_public_hostname}
endif::[]

ifeval::["{cloud_provider}" == "openshift_cnv"]
ssh {user}@{bastion_public_hostname} -p {bastion_ssh_port}
endif::[]
----

[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

Once connected to the bastion host and OCP cluster run the command to break the lab.

[source,sh,role=execute,subs="attributes"]
----
lab break exercise4
----