[#fix]
= Fix Virtual Machine snapshot restore buttons are grayed out

== Scenario

In this scenario, a Virtual Machine named `exercise8` is currently in the `Running` state and has an existing snapshot that the user wants to restore. However, the user has noticed that the buttons to restore the snapshot are grayed out, making it impossible to proceed with the restoration.

Your task is to investigate the steps taken by the user to restore the snapshot and resolve the issue.

The steps to fix exercise8 are:

== Console
----
1. Login to Openshift console using the assigned user account
2. Go to virtualization - virtual machine - select project for the assigned user account - look for VM status

#TODO

----

== Command line (CLI)
- Login to Openshift server API using the assigned user account with `oc` command if not logged in

[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

- Go to assigned namespace-{user}

[source,sh,role=execute,subs="attributes"]
----
oc project namespace-{user}
----

- Check that ssh is not working

[source,sh,role=execute,subs="attributes"]
----
virtctl ssh lab-user@exercise8
----

- Expected output

[source,subs="attributes"]
----
Warning: Permanently added 'vmi/exercise8.namespace-{user}' (ED25519) to the list of known hosts.
lab-user@vmi/exercise8.namespace-{user}: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
exit status 255
----


- Add the user SSH key to `exercise8` virtual machine using `virtctl`

[source,sh,role=execute,subs="attributes"]
----
virtctl credentials add-ssh-key -f /home/{user}/.ssh/id_rsa.pub --user lab-user --force exercise8
----

- the output will be.

[source]
----
 Successfully added the key to secret "idrsa"
----

- Get the pod name

[source,sh,role=execute,subs="attributes"]
PODNAME=$(oc get pods -l kubevirt.io/domain=exercise8 -o NAME -n namespace-{user}})

- Check the logs and wait for the message on virtual machine pod

[source]
----
{"component":"virt-launcher","kind":"","level":"info","msg":"Reloading access credentials because secret changed","name":"exercise8","namespace":"namespace-user5","pos":"access_credentials.go:448","timestamp":"2024-11-25T18:47:52.185346Z","uid":"728e56da-dff5-400d-8967-fe406e4ca72f"}
----

[source,sh,role=execute,subs="attributes"]
----
oc logs $POD_NAME -n namespace-{user}
----

- Test the SSH access

[source,sh,role=execute,subs="attributes"]
----
virtctl ssh lab-user@exercise8
----