[#scenario]
= Add a new SSH key to a virtual machine

== Scenario

In this scenario, an RHEL 9-based Virtual Machine (VM) named `exercise8` is currently in the `Running` state. The team has identified that the SSH key created by this VM has been lost. To regain SSH access, a new SSH key must be added to the VM.  

=== Constraints
- Access to the VM via the console is not possible because the user `lab-user` does not have password defined.
- The new SSH key to be added is located at `/home/{user}/.ssh/id_rsa.pub`.

=== Task
Perform the necessary steps to add the specified SSH key to the `exercise8` VM to restore remote access.  

NOTE: The primary goal is to get access to the `exercise8` via SSH virtual machine restored.

TIP: Use `virtctl ssh lab-user@exercise8` command to test the access.

== Executing the lab script

In this exercise setup, ensure you are logged in to the bastion and OCP cluster as {user}

[source,sh,role=execute,subs="attributes"]
----
ifeval::["{cloud_provider}" == "gcp"]
ssh {user}@{bastion_public_hostname}
endif::[]

ifeval::["{cloud_provider}" == "openshift_cnv"]
ssh {user}@{bastion_public_hostname} -p {bastion_ssh_port}
endif::[]
----

[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

Once connected to the bastion host and OCP cluster run the command to break the lab.

[source,sh,role=execute,subs="attributes"]
----
lab break exercise8
----

== Console

After completing the break, you can access the OpenShift web console using the username `{user}` and password `{password}`.

link:https://console-openshift-console.apps.cluster-{guid}.dynamic.redhatworkshops.io[https://console-openshift-console.apps.cluster-{guid}.dynamic.redhatworkshops.io^]

++++
</br>
<div>
  <code id="user">Username: {user}</code>
  <button onclick="copyToClipboard('user')">Copy Username</button>
</div>
</br>
<div>
  <code id="password">Password: {password}</code>
  <button onclick="copyToClipboard('password')">Copy Password</button>
</div>
<script>
  function copyToClipboard(id) {
    const textToCopy = document.getElementById(id).textContent.replace(/^.*:\s/, '');
    navigator.clipboard.writeText(textToCopy).catch(err => {
      console.error('Failed to copy: ', err);
    });
  }
</script>
++++