[#fix]
= Fix Application is not being accessed externally

== Scenario

The application is running on a virtual machine `exercise3` and is intended to be accessible externally through https://exercise3-namespace-{user}.apps.cluster-{guid}.dynamic.redhatworkshops.io, but it’s currently facing connectivity issues.

The primary goal in this scenario is to investigate the cause of the issue by examining the OpenShift network components involved in accessing the application within the OpenShift cluster.

Your task is to identify the root cause and resolve the issue.

The steps to fix exercise3 are:

== Console
----
1. Login to Openshift console using the assigned user account
2. Go to virtualization - virtual machine - select project for the assigned user account - look for VM status
3. Go to Networking - look for the name exercise3 and location - click the location (https route)
4. In the new browser tab - check the error status (The application is currently not serving requests at this endpoint. It may not have been started or is still starting.)
5. Go to Network - Services - Check exercise3 services - Look for target port (80) and IP
6. Go to Workloads - Pod - Select curlimage pod - Terminal
7. Try to do curl from the pod to service IP and port (80)
8. The service should be accessible with message: Hello from exercise3, you are doing a great job!
9. Go to Network - Routes - Check exercise3 routes - Look for target port (8080)
10. Edit route for exercise3 in yaml and update the target port into 80 - Save
11. Access the route URL and application should be accessible
----

== Command Line (CLI)

1. Login to Openshift server API using the assigned user account with `oc` command if not logged in.

[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

[start=2]
2. Go to the assigned namespace-{user}

[source,sh,role=execute,subs="attributes"]
----
oc project namespace-{user}
----

[start=3]
3.  Get the Virtual Machine pod IP address

[source,sh,role=execute,subs="attributes"]
----
PODIP=$(oc get pods -l kubevirt.io/domain=exercise3 -o jsonpath="{.items[*].status.podIP}" -n namespace-user5)
----

[start=4]
4. Use the curlimage pod to test the Virtual Machine and verify that it's working as expected

[source,sh,role=execute,subs="attributes"]
----
oc exec curlimage -- curl -s $PODIP
----

[source]
----
Hello from exercise3, you are doing a great job!
----

[start=5]
5. Check the service details of exercise3 and get details for IP and Port

[source,sh,role=execute,subs="attributes"]
----
SVCIP=$(oc get svc exercise3 -o jsonpath="{.spec.clusterIP}" -n namespace-user5)
----

[start=6]
6. Curl the IP and port from service in the curlimage pod

[source,sh,role=execute,subs="attributes"]
----
oc exec curlimage -- curl -s $SVCIP
----

[source]
----
Hello from exercise3, you are doing a great job!
----

[start=7]
7. Try to access the route and verify that it's not working

[source,sh,role=execute,subs="attributes"]
----
oc exec curlimage -- curl -s https://exercise3-namespace-{user}.apps.cluster-{guid}.dynamic.redhatworkshops.io
----

[start=8]
8. Check the route and verify that Wrong `Endpoint Port` (8080)

[source,sh,role=execute,subs="attributes"]
----
oc describe route exercise3
----

[start=9]
9. Edit the route exercise3 and change `targetPort` from 8080 to 80

[source,sh,role=execute,subs="attributes"]
----
oc edit route exercise3
----

[start=10]10. 
or just use this patch

[source,sh,role=execute,subs="attributes"]
----
oc patch route exercise3 -p '{"spec":{"port":{"targetPort":80}}}'
----

[start=11]
11. Test the application

NOTE: The application is available on https://exercise3-namespace-{user}.apps.cluster-{guid}.dynamic.redhatworkshops.io

or 

[source,sh,role=execute,subs="attributes"]
----
oc exec curlimage -- curl -s https://exercise3-namespace-{user}.apps.cluster-{guid}.dynamic.redhatworkshops.io
----