[#scenario]
= The VM doesn't stop when shutdown is run inside the guest OS

== Scenario

The virtual machine `exercise9` is not powered off after the user executes a `shutdown -h now` command within the guest OS. A few seconds after the shutdown process, it automatically powers back on.

NOTE: You need to modify the Virtual Machine configuration to ensure it remains in a stopped state after shutdown using guest OS.

== Executing the lab script

In this exercise setup, ensure you are logged in to the bastion with password `{bastion_ssh_port}` and OpenShift cluster as user `{user}`.

.SSH command to Bastion
[source,sh,role=execute,subs="attributes"]
----
ifeval::["{cloud_provider}" == "gcp"]
ssh {user}@{bastion_public_hostname}
endif::[]

ifeval::["{cloud_provider}" == "openshift_cnv"]
ssh {user}@{bastion_public_hostname} -p {bastion_ssh_port}
endif::[]
----

.Bastion Password
[source,sh,role=execute,subs="attributes"]
----
{bastion_ssh_password}
----

.OpenShift login command
[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

Once connected to the bastion host and OCP cluster run the command to break the lab.

.Breaking the exercise
[source,sh,role=execute,subs="attributes"]
----
lab break exercise9
----

=== Console
After completing the break, you can access the OpenShift web console using the username and password.

link:{openshift_console_url}[{openshift_console_url}^]

.Username
[source,sh,role=execute,subs="attributes"]
----
{user}
----

.Password
[source,sh,role=execute,subs="attributes"]
----
{password}
----