[#scenario]
= Additional disk unaccessible in Virtual Machine

== Scenario

The user is reporting that the additional disk in the `exercise5` virtual machine does not show up in the lists when running the `fdisk` or `lsblk` command. The user would like to create a disk named `exercise5-vol-data1` and mount it to the virtual machine named `exercise5`

NOTE: Your task is to troubleshoot and resolve the issue so that the `exercise5-vol-data1` disk is showing when the user runs the `lsblk` or `fdisk` command.

== Executing the lab script

In this exercise setup, ensure you are logged in to the bastion with password `{bastion_ssh_password}` and OpenShift cluster as user `{user}`.

.SSH command to bastion
[source,sh,role=execute,subs="attributes"]
----
ifeval::["{cloud_provider}" == "gcp"]
ssh {user}@{bastion_public_hostname}
endif::[]

ifeval::["{cloud_provider}" == "openshift_cnv"]
ssh {user}@{bastion_public_hostname} -p {bastion_ssh_port}
endif::[]
----

.bastion Password
[source,sh,role=execute,subs="attributes"]
----
{bastion_ssh_password}
----

.OpenShift login command
[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

Once connected to the bastion host and OCP cluster run the command to break the lab.

.Breaking the exercise
[source,sh,role=execute,subs="attributes"]
----
lab break exercise5
----

=== Console
After the break, you can log in to the OpenShift web console using your username and password or continue using the `oc` command line at bastion to begin the troubleshooting process.

link:{openshift_console_url}[{openshift_console_url}^]

.Username
[source,sh,role=execute,subs="attributes"]
----
{user}
----

.Password
[source,sh,role=execute,subs="attributes"]
----
{password}
----
