[#scenario]
= Virtual Machine with performance degraded

== Scenario

The development team has reported a performance issue with an application running inside the virtual machine `exercise4` and you need to investigate the problem. 
The initial analysis will involve examining virtual machine resource usage, such as CPU, memory, and disk I/O. Changing compute resources are available in this lab but `no reboot` is mandatory.

The goal is to identify any bottlenecks or misconfigurations and implement optimizations to enhance the application's efficiency within the virtualized infrastructure.

== Executing the lab script

In this exercise setup, you first need to access the bastion trough `{bastion_public_hostname}` to gain entry into the lab environment. From the terminal, access SSH the node bastion if you are not connected yet.

[source,sh,role=execute]
```
ssh {user}@{bastion_public_hostname} -p {bastion_ssh_port}
```

Once connected to the bastion host run the command to break the lab.

[source,sh,role=execute]
```
lab break exercise4