[#scenario]
= Additional disk unaccessible in Virtual Machine

== Scenario

The user is reporting that the additional disk in the `exercise5` virtual machine does not show up in the lists when running the `fdisk` or `lsblk` command. The user would like to create a disk named `exercise5-vol-data1` and mount it to the virtual machine named `exercise5`

NOTE: Your task is to troubleshoot and resolve the issue so that the `exercise5-vol-data1` disk is showing when the user runs the `lsblk` or `fdisk` command.

== Executing the lab script

In this exercise setup, ensure you are logged in to the bastion with password {bastion_ssh_port}

[source,sh,role=execute,subs="attributes"]
----
ifeval::["{cloud_provider}" == "gcp"]
ssh {user}@{bastion_public_hostname}
endif::[]

ifeval::["{cloud_provider}" == "openshift_cnv"]
ssh {user}@{bastion_public_hostname} -p {bastion_ssh_port}
endif::[]
----

[source,sh,role=execute,subs="attributes"]
----
{bastion_ssh_password}
----

and OCP cluster as {user}

[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

Once connected to the bastion host and OCP cluster run the command to break the lab.

[source,sh,role=execute]
----
lab break exercise5
----

== Console

After completing the break, you can access the OpenShift web console using the username `{user}` and password `{password}`.

link:https://console-openshift-console.apps.cluster-{guid}.dynamic.redhatworkshops.io[https://console-openshift-console.apps.cluster-{guid}.dynamic.redhatworkshops.io^]

++++
</br>
<div>
  <code id="user">Username: {user}</code>
  <button onclick="copyToClipboard('user')">Copy Username</button>
</div>
</br>
<div>
  <code id="password">Password: {password}</code>
  <button onclick="copyToClipboard('password')">Copy Password</button>
</div>
<script>
  function copyToClipboard(id) {
    const textToCopy = document.getElementById(id).textContent.replace(/^.*:\s/, '');
    navigator.clipboard.writeText(textToCopy).catch(err => {
      console.error('Failed to copy: ', err);
    });
  }
</script>
++++
