[#scenario]
= Add a new SSH key to a virtual machine

== Scenario

In this scenario, an RHEL 9-based Virtual Machine (VM) named `exercise8` is currently in the `Running` state. The team has identified that the SSH key created by this VM has been lost. To regain SSH access, a new SSH key must be added to the VM.  

=== Constraints
- Access to the VM via the console is not possible because the user `lab-user` does not have password defined.
- The new SSH key to be added is located at `/home/{user}/.ssh/id_rsa.pub`.

=== Task
Perform the necessary steps to add the specified SSH key to the `exercise8` VM to restore remote access.  

NOTE: The primary goal is to get access to the `exercise8` via SSH virtual machine restored.

TIP: Use `virtctl ssh lab-user@exercise8` command to test the access.

== Executing the lab script

In this exercise setup, ensure you are logged in to the bastion with password `{bastion_ssh_password}` and OpenShift cluster as user `{user}`.

.SSH command to bastion
[source,sh,role=execute,subs="attributes"]
----
ifeval::["{cloud_provider}" == "gcp"]
ssh {user}@{bastion_public_hostname}
endif::[]

ifeval::["{cloud_provider}" == "openshift_cnv"]
ssh {user}@{bastion_public_hostname} -p {bastion_ssh_port}
endif::[]
----

.bastion Password
[source,sh,role=execute,subs="attributes"]
----
{bastion_ssh_password}
----

.OpenShift login command
[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

Once connected to the bastion host and OCP cluster run the command to break the lab.

.Breaking the exercise
[source,sh,role=execute,subs="attributes"]
----
lab break exercise8
----

=== Console
After the break, you can log in to the OpenShift web console using your username and password or continue using the `oc` command line at bastion to begin the troubleshooting process.

link:{openshift_console_url}[{openshift_console_url}^]

.Username
[source,sh,role=execute,subs="attributes"]
----
{user}
----

.Password
[source,sh,role=execute,subs="attributes"]
----
{password}
----