[#scenario]
= Additional disk unaccessible in Virtual Machine

== Scenario

The user is reporting that the additional disk in the `exercise5` virtual machine does not show up in the lists when running the `fdisk` or `lsblk` command. The user would like to create a disk named `exercise5-vol-data1` and mount it to the virtual machine named `exercise5`

NOTE: Your task is to troubleshoot and resolve the issue so that the `exercise5-vol-data1` disk is showing when the user runs the `lsblk` or `fdisk` command.

== Executing the lab script

In this exercise setup, ensure you are logged in to OpenShift cluster as user `{user}`.

.OpenShift login command
[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

Once connected to the OCP cluster, run the command to break the lab.

.Breaking the exercise
[source,sh,role=execute,subs="attributes"]
----
lab break exercise5
----

=== Console
After the break, you can log in to the OpenShift web console using your username and password or continue using the `oc` Command line at bastion to begin the troubleshooting process.

link:{openshift_console_url}[{openshift_console_url}^]

.Username
[source,sh,role=execute,subs="attributes"]
----
{user}
----

.Password
[source,sh,role=execute,subs="attributes"]
----
{password}
----
